export const mockProducts = [

    {
      id: 2,
      imageUrl:
        "https://img.freepik.com/free-photo/handbag-isolated_1203-7955.jpg",
      name: "Elegant Handbag",
      discountRate: 30,
      originalPrice: 249.99,
      rating: 4.5,
      reviewCount: 89,
    },
    {
      id: 3,
      imageUrl:
        "https://img.freepik.com/free-photo/blue-jeans-isolated_1203-7954.jpg",
      name: "Classic Blue Jeans",
      discountRate: null,
      originalPrice: 79.99,
      rating: 4,
      reviewCount: 34,
    },
    {
      id: 4,
      imageUrl:
        "https://img.freepik.com/free-photo/black-leather-boots-isolated_1203-7967.jpg",
      name: "Leather Boots",
      discountRate: 20,
      originalPrice: 150,
      rating: 4.8,
      reviewCount: 78,
    },
    {
      id: 5,
      imageUrl:
        "https://img.freepik.com/free-photo/sunglasses-isolated_1203-7696.jpg",
      name: "Aviator Sunglasses",
      discountRate: 15,
      originalPrice: 85,
      rating: 3.5,
      reviewCount: 43,
    },
    {
        id: 6,
        imageUrl: "https://img.freepik.com/free-photo/modern-smart-watch-isolated_1203-7965.jpg",
        name: "Smart Watch",
        discountRate: 10,
        originalPrice: 299,
        rating: 4.2,
        reviewCount: 120,
      },
      {
        id: 7,
        imageUrl: "https://img.freepik.com/free-photo/headphones-isolated_1203-7969.jpg",
        name: "Wireless Headphones",
        discountRate: 25,
        originalPrice: 199,
        rating: 4.7,
        reviewCount: 88,
      },
      {
        id: 8,
        imageUrl: "https://img.freepik.com/free-photo/vintage-camera-isolated_1203-7959.jpg",
        name: "Vintage Camera",
        discountRate: 15,
        originalPrice: 450,
        rating: 3.9,
        reviewCount: 47,
      },
      {
        id: 9,
        imageUrl: "https://img.freepik.com/free-photo/red-sports-sneakers-isolated_1203-7970.jpg",
        name: "Red Sports Sneakers",
        discountRate: 20,
        originalPrice: 130,
        rating: 4.3,
        reviewCount: 56,
      },
      {
        id: 10,
        imageUrl: "https://img.freepik.com/free-photo/tablet-isolated_1203-7968.jpg",
        name: "Tablet",
        discountRate: 5,
        originalPrice: 600,
        rating: 4.0,
        reviewCount: 150,
      },
      {
        id: 11,
        imageUrl: "https://img.freepik.com/free-photo/gaming-mouse-isolated_1203-7971.jpg",
        name: "Gaming Mouse",
        discountRate: null,
        originalPrice: 70,
        rating: 4.6,
        reviewCount: 90,
      },
      {
        id: 12,
        imageUrl: "https://img.freepik.com/free-photo/colorful-backpack-isolated_1203-7972.jpg",
        name: "Colorful Backpack",
        discountRate: 10,
        originalPrice: 49.99,
        rating: 3.8,
        reviewCount: 33,
      },
      {
        id: 13,
        imageUrl: "https://img.freepik.com/free-photo/yoga-mat-isolated_1203-7966.jpg",
        name: "Yoga Mat",
        discountRate: 20,
        originalPrice: 35,
        rating: 4.5,
        reviewCount: 40,
      },
      {
        id: 14,
        imageUrl: "https://img.freepik.com/free-photo/water-bottle-isolated_1203-7973.jpg",
        name: "Water Bottle",
        discountRate: null,
        originalPrice: 25,
        rating: 4.1,
        reviewCount: 67,
      },
      {
        id: 15,
        imageUrl: "https://img.freepik.com/free-photo/microphone-isolated_1203-7958.jpg",
        name: "Studio Microphone",
        discountRate: 5,
        originalPrice: 99,
        rating: 4.4,
        reviewCount: 52,
      }
  ];
